language: node_js
node_js:
  - '7'
  - '6'
  - '4'

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules

before_install: 'yarn'
script: 'yarn test'
after_script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
